spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: ${URL:jdbc}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    port: 6379
    host: 

jwt:
  header: ${HEADER:Authorization}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:HudYB&d-kl}
  accessExp: ${JWT_ACCESS_EXP:3600}
  refreshExp: ${JWT_REFRESH_EXP:4800}


logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS-KEY}
      secretKey: ${SECRET-KEY}
    s3:
      bucket: ${BUCKET}
    region:
      static: ${STATIC}

  stack:
    auto: false
